# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-17 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160517_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='description',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='painting',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
